"""Generate a cheap local 2D map from TF-IDF profile text."""

from __future__ import annotations

import csv
import html
import json
from dataclasses import dataclass
from pathlib import Path

import numpy as np
from sklearn.decomposition import TruncatedSVD
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

from film_atlas.models import MapPoint, NeighborPair, SemanticProfile
from film_atlas.profiles import load_profiles

MAP_CSV_FILENAME = "sample_map.csv"
MAP_JSON_FILENAME = "sample_map.json"
MAP_HTML_FILENAME = "sample_map.html"
NEIGHBORS_FILENAME = "nearest_neighbors.json"


@dataclass(frozen=True, slots=True)
class SampleMapResult:
    """Paths and records generated by the sample map step."""

    points: list[MapPoint]
    neighbor_pairs: list[NeighborPair]
    csv_path: Path
    json_path: Path
    html_path: Path
    neighbors_path: Path


def make_sample_map_file(
    *,
    profiles_path: str | Path = "data/processed/profiles.json",
    output_dir: str | Path = "outputs",
) -> SampleMapResult:
    """Create CSV, JSON, HTML, and nearest-neighbor outputs for the sample map."""
    profiles = load_profiles(profiles_path)
    result = build_sample_map(profiles)

    reports_dir = Path(output_dir) / "reports"
    figures_dir = Path(output_dir) / "figures"
    reports_dir.mkdir(parents=True, exist_ok=True)
    figures_dir.mkdir(parents=True, exist_ok=True)

    csv_path = reports_dir / MAP_CSV_FILENAME
    json_path = reports_dir / MAP_JSON_FILENAME
    html_path = figures_dir / MAP_HTML_FILENAME
    neighbors_path = reports_dir / NEIGHBORS_FILENAME

    _write_points_csv(csv_path, result.points)
    json_path.write_text(
        json.dumps([point.to_dict() for point in result.points], indent=2, sort_keys=True),
        encoding="utf-8",
    )
    neighbors_path.write_text(
        json.dumps([pair.to_dict() for pair in result.neighbor_pairs], indent=2, sort_keys=True),
        encoding="utf-8",
    )
    html_path.write_text(render_sample_map_html(result.points), encoding="utf-8")

    return SampleMapResult(
        points=result.points,
        neighbor_pairs=result.neighbor_pairs,
        csv_path=csv_path,
        json_path=json_path,
        html_path=html_path,
        neighbors_path=neighbors_path,
    )


def build_sample_map(profiles: list[SemanticProfile]) -> SampleMapResult:
    """Build TF-IDF/SVD coordinates and nearest-neighbor pairs."""
    if not profiles:
        points: list[MapPoint] = []
        pairs: list[NeighborPair] = []
        placeholder = Path("")
        return SampleMapResult(points, pairs, placeholder, placeholder, placeholder, placeholder)

    texts = [profile.profile_text or profile.title for profile in profiles]
    vectorizer = TfidfVectorizer(
        stop_words="english",
        max_features=5000,
        ngram_range=(1, 2),
        min_df=1,
    )
    matrix = vectorizer.fit_transform(texts)
    feature_names = np.array(vectorizer.get_feature_names_out())

    coords = _reduce_to_2d(matrix)
    points = [
        MapPoint(
            tmdb_id=profile.tmdb_id,
            title=profile.title,
            year=profile.year,
            x=float(coords[index, 0]),
            y=float(coords[index, 1]),
            top_terms=_top_terms_for_row(matrix[index], feature_names),
        )
        for index, profile in enumerate(profiles)
    ]
    pairs = _nearest_neighbor_pairs(profiles, matrix)

    placeholder = Path("")
    return SampleMapResult(points, pairs, placeholder, placeholder, placeholder, placeholder)


def render_sample_map_html(points: list[MapPoint]) -> str:
    """Render a small standalone SVG scatterplot for quality checks."""
    width = 900
    height = 620
    margin = 48
    if not points:
        body = "<p>No sample map points were generated.</p>"
    else:
        xs = [point.x for point in points]
        ys = [point.y for point in points]
        min_x, max_x = min(xs), max(xs)
        min_y, max_y = min(ys), max(ys)

        circles = []
        for point in points:
            cx = _scale(point.x, min_x, max_x, margin, width - margin)
            cy = _scale(point.y, min_y, max_y, height - margin, margin)
            title = html.escape(f"{point.title} ({point.year or 'unknown'})")
            terms = html.escape(", ".join(point.top_terms))
            circles.append(
                f'<circle cx="{cx:.2f}" cy="{cy:.2f}" r="5">'
                f"<title>{title}: {terms}</title></circle>"
            )
        body = (
            f'<svg viewBox="0 0 {width} {height}" role="img" '
            'aria-label="Film Atlas sample map">'
            "<rect width=\"100%\" height=\"100%\" fill=\"#f8f7f3\" />"
            "<g fill=\"#2563eb\" fill-opacity=\"0.72\" stroke=\"#172554\" "
            f"stroke-width=\"0.8\">{''.join(circles)}</g></svg>"
        )

    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>The Film Atlas - Milestone 1 Sample Map</title>
  <style>
    body {{
      margin: 0;
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      background: #f8f7f3;
      color: #111827;
    }}
    main {{
      max-width: 980px;
      margin: 0 auto;
      padding: 32px 18px;
    }}
    h1 {{
      font-size: 24px;
      font-weight: 650;
    }}
    svg {{
      width: 100%;
      height: auto;
      border: 1px solid #d8d5cc;
    }}
  </style>
</head>
<body>
  <main>
    <h1>The Film Atlas - Milestone 1 Sample Map</h1>
    {body}
  </main>
</body>
</html>
"""


def _reduce_to_2d(matrix: object) -> np.ndarray:
    n_rows, n_features = matrix.shape
    if n_rows == 1:
        return np.array([[0.0, 0.0]])
    if n_features == 1:
        values = matrix.toarray()[:, 0]
        return np.column_stack([values, np.zeros(n_rows)])

    components = min(2, n_features)
    coords = TruncatedSVD(n_components=components, random_state=42).fit_transform(matrix)
    if coords.shape[1] == 1:
        coords = np.column_stack([coords[:, 0], np.zeros(n_rows)])
    return coords


def _top_terms_for_row(row: object, feature_names: np.ndarray, *, limit: int = 6) -> list[str]:
    values = row.toarray().ravel()
    if not np.any(values):
        return []
    top_indexes = values.argsort()[::-1][:limit]
    return [str(feature_names[index]) for index in top_indexes if values[index] > 0]


def _nearest_neighbor_pairs(
    profiles: list[SemanticProfile],
    matrix: object,
    *,
    limit: int = 10,
) -> list[NeighborPair]:
    if len(profiles) < 2:
        return []

    similarity_matrix = cosine_similarity(matrix)
    pairs = []
    for source_index, source in enumerate(profiles):
        for neighbor_index in range(source_index + 1, len(profiles)):
            neighbor = profiles[neighbor_index]
            pairs.append(
                NeighborPair(
                    source_tmdb_id=source.tmdb_id,
                    source_title=source.title,
                    neighbor_tmdb_id=neighbor.tmdb_id,
                    neighbor_title=neighbor.title,
                    similarity=float(similarity_matrix[source_index, neighbor_index]),
                )
            )

    return sorted(pairs, key=lambda pair: pair.similarity, reverse=True)[:limit]


def _write_points_csv(path: Path, points: list[MapPoint]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=["tmdb_id", "title", "year", "x", "y", "top_terms"],
        )
        writer.writeheader()
        for point in points:
            row = point.to_dict()
            row["top_terms"] = "; ".join(point.top_terms)
            writer.writerow(row)


def _scale(value: float, source_min: float, source_max: float, dest_min: float, dest_max: float) -> float:
    if source_min == source_max:
        return (dest_min + dest_max) / 2
    ratio = (value - source_min) / (source_max - source_min)
    return dest_min + ratio * (dest_max - dest_min)
